// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7QiwGiFo79xHkh0777CespP_FMxWKIAc',
    appId: '1:739872792509:web:6a17c1e197982e8b193cd4',
    messagingSenderId: '739872792509',
    projectId: 'mon-app1',
    authDomain: 'mon-app1.firebaseapp.com',
    storageBucket: 'mon-app1.firebasestorage.app',
    measurementId: 'G-P0SCQ4J3MP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfhL6lpx5E-8WRMSwr6-h9-FTb_rp_sx0',
    appId: '1:739872792509:android:3d8662dd1a834721193cd4',
    messagingSenderId: '739872792509',
    projectId: 'mon-app1',
    storageBucket: 'mon-app1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoD7hvD-XbwJAIWaw1R4km-UJy669mjS8',
    appId: '1:739872792509:ios:6284563a7acbf2ce193cd4',
    messagingSenderId: '739872792509',
    projectId: 'mon-app1',
    storageBucket: 'mon-app1.firebasestorage.app',
    iosBundleId: 'com.example.monApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoD7hvD-XbwJAIWaw1R4km-UJy669mjS8',
    appId: '1:739872792509:ios:6284563a7acbf2ce193cd4',
    messagingSenderId: '739872792509',
    projectId: 'mon-app1',
    storageBucket: 'mon-app1.firebasestorage.app',
    iosBundleId: 'com.example.monApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7QiwGiFo79xHkh0777CespP_FMxWKIAc',
    appId: '1:739872792509:web:062d9abc97e48077193cd4',
    messagingSenderId: '739872792509',
    projectId: 'mon-app1',
    authDomain: 'mon-app1.firebaseapp.com',
    storageBucket: 'mon-app1.firebasestorage.app',
    measurementId: 'G-2HSL3HNB8S',
  );
}
